"""Dose-response comparison across noise-ratio experiments (e.g. ratio10 vs ratio05).

Aggregates per-tag evaluation results, detection AUC tables and held-out
loss trajectories into a side-by-side comparison document (zh + en).

Usage:
  python scripts/compare_ratios.py --tags ratio10,ratio05
"""

import argparse
import json
import os

import numpy as np
import pandas as pd

DATASETS = ["clean", "garbled", "duplicate", "unrelated", "keyword", "mixed"]
NOISE_TYPES = ["garbled", "duplicate", "unrelated", "keyword", "mixed"]
EVAL_TASKS = ["mmlu", "gsm8k", "hellaswag", "arc", "bbh", "truthfulqa", "winogrande"]


def load_eval(repo, tag, ds):
    p = os.path.join(repo, "results", "eval", f"eval_{tag}_{ds}.json")
    if not os.path.exists(p):
        return None
    r = json.load(open(p))
    return {t: r.get(t, {}).get("acc") if isinstance(r.get(t), dict) else r.get(t)
            for t in EVAL_TASKS}


def load_auc(repo, tag):
    p = os.path.join(repo, "results", f"auc_univariate_{tag}.csv")
    if not os.path.exists(p):
        return None
    return pd.read_csv(p).set_index("noise_type")


def load_multi_auc(repo, tag):
    p = os.path.join(repo, "results", f"detection_multivariate_{tag}.csv")
    if not os.path.exists(p):
        return None
    d = pd.read_csv(p)
    return d[d["model"] == "LR"].set_index("noise_type")["auc"]


def load_heldout(repo, tag):
    p = os.path.join(repo, "results", f"tb_heldout_loss_{tag}.csv")
    if not os.path.exists(p):
        return None
    return pd.read_csv(p).set_index("step").apply(lambda c: c.dropna().iloc[-1])


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", default="/root/noisedetect/config.yaml")
    ap.add_argument("--tags", default="ratio10,ratio05")
    args = ap.parse_args()
    import yaml
    cfg = yaml.safe_load(open(args.config))
    repo = cfg["paths"]["repo_root"]
    tags = [t.strip() for t in args.tags.split(",")]
    docs = os.path.join(repo, "docs")

    # ---- eval comparison ----
    rows = []
    for tag in tags:
        for ds in DATASETS + ["base"]:
            r = load_eval(repo, tag, ds)
            if r:
                rows.append({"tag": tag, "model": ds, **r})
    ev_tab = pd.DataFrame(rows)

    # ---- detection ----
    aucs = {t: load_auc(repo, t) for t in tags}
    multis = {t: load_multi_auc(repo, t) for t in tags}
    held = {t: load_heldout(repo, t) for t in tags}

    def fmt(x):
        return "—" if x is None or (isinstance(x, float) and x != x) else f"{x:.4f}"

    lines_zh = ["""# 剂量-效应对比: ratio10 vs ratio05

> 由 `compare_ratios.py` 自动生成 · 检测特征 19 维 · 训练配置与 ratio10 完全一致 (仅噪音比例不同)

## 1. 检测 AUC (单指标最优 + LR 分类器)

| 噪音类型 | 最优单指标 AUC (10%) | 最优单指标 AUC (5%) | LR AUC (10%) | LR AUC (5%) |
|---|---|---|---|---|
"""]
    best_metrics = ["loss_curvature", "user_loss", "entropy", "text_nn_sim"]
    for nt in NOISE_TYPES:
        def best_auc(tag):
            a = aucs.get(tag)
            if a is None or nt not in a.index:
                return None
            row = a.loc[nt].dropna()
            return row.max() if len(row) else None
        lines_zh.append(f"| {nt} | {fmt(best_auc(tags[0]))} | {fmt(best_auc(tags[1]))} | "
                        f"{fmt((multis.get(tags[0]) or {}).get(nt))} | {fmt((multis.get(tags[1]) or {}).get(nt))} |")

    lines_zh.append("""
## 2. 验证集对比 (微调模型, 按 tag)

| tag | 模型 | MMLU | GSM8K | HellaSwag | ARC | BBH | TruthfulQA | Winogrande |
|---|---|---|---|---|---|---|---|---|
""")
    for _, r in ev_tab.iterrows():
        vals = " | ".join(fmt(r[t]) for t in EVAL_TASKS)
        lines_zh.append(f"| {r['tag']} | {r['model']} | {vals} |")

    lines_zh.append("""
## 3. Held-out 最终损失

| run | """ + " | ".join(tags) + """ |
|---|---|---|
""")
    for ds in DATASETS:
        lines_zh.append(f"| {ds} | " + " | ".join(fmt(held[t].get(ds)) if held.get(t) is not None else "—" for t in tags) + " |")

    lines_zh.append("""
## 4. 初步结论 (待人工完善)

- 检测 AUC 是否随比例下降 (验证训练内检测力的比例敏感性);
- 危害是否近似线性 (5% vs 10% 的验证集差);
- duplicate 的方向反转是否在 5% 仍成立。
""")
    open(os.path.join(docs, "dose_response_zh.md"), "w").write("\n".join(lines_zh))

    lines_en = ["""# Dose-response comparison: ratio10 vs ratio05

> Auto-generated by `compare_ratios.py` · identical training setup except the noise ratio

## 1. Detection AUC (best univariate + LR classifier)

| Noise type | best metric AUC (10%) | best metric AUC (5%) | LR AUC (10%) | LR AUC (5%) |
|---|---|---|---|---|
"""]
    for nt in NOISE_TYPES:
        def best_auc(tag):
            a = aucs.get(tag)
            if a is None or nt not in a.index:
                return None
            row = a.loc[nt].dropna()
            return row.max() if len(row) else None
        lines_en.append(f"| {nt} | {fmt(best_auc(tags[0]))} | {fmt(best_auc(tags[1]))} | "
                        f"{fmt((multis.get(tags[0]) or {}).get(nt))} | {fmt((multis.get(tags[1]) or {}).get(nt))} |")

    lines_en.append("""
## 2. Benchmark comparison (fine-tuned models)

| tag | model | MMLU | GSM8K | HellaSwag | ARC | BBH | TruthfulQA | Winogrande |
|---|---|---|---|---|---|---|---|---|
""")
    for _, r in ev_tab.iterrows():
        vals = " | ".join(fmt(r[t]) for t in EVAL_TASKS)
        lines_en.append(f"| {r['tag']} | {r['model']} | {vals} |")

    lines_en.append("""
## 3. Final held-out loss

| run | """ + " | ".join(tags) + """ |
|---|---|---|
""")
    for ds in DATASETS:
        lines_en.append(f"| {ds} | " + " | ".join(fmt(held[t].get(ds)) if held.get(t) is not None else "—" for t in tags) + " |")

    lines_en.append("""
## 4. Preliminary takeaways (to refine)

- Does detection AUC decay with the ratio (ratio-sensitivity of online detection)?
- Is the harm roughly linear between 5% and 10%?
- Does duplicate's inverted direction hold at 5%?
""")
    open(os.path.join(docs, "dose_response_en.md"), "w").write("\n".join(lines_en))
    print(f"dose-response docs written to {docs}/dose_response_{{zh,en}}.md")
    if ev_tab.empty:
        print("WARN: no eval data found for any tag yet")


if __name__ == "__main__":
    main()
